[default]
# General
max_sequence_length = 512
question_number = 2

# Context Retrieval
number_of_retrieved_contexts = 5

# Question Answering
num_generated_answers = 5
num_correct_answers_required = 3

# Processing 
## Translation
input_language = "en"

